package Telas;

import DAO.CadastrarCliente;
import javabeans.Moto;
import javabeans.Marca;
import javabeans.Modelo;
import javax.swing.JOptionPane;

/**
 *
 * @author Arthur, Gustavo e Ulisses
 */
public class CadastroJogo extends javax.swing.JFrame {

    /**
     * Creates new form formPrincipal
     */
    public CadastroJogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpIdade1 = new javax.swing.JPanel();
        jcb1 = new javax.swing.JCheckBox();
        jcb2 = new javax.swing.JCheckBox();
        codigo = new javax.swing.JLabel();
        jrbF = new javax.swing.JRadioButton();
        btnSalvar = new javax.swing.JButton();
        sexo = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        quantidade = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        idade = new javax.swing.JLabel();
        jrbM = new javax.swing.JRadioButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Preco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        KmRodado = new javax.swing.JTextField();
        Salvar1 = new javax.swing.JButton();
        inserir = new javax.swing.JButton();
        HONDA = new javax.swing.JRadioButton();
        BMW = new javax.swing.JRadioButton();
        YAMAHA = new javax.swing.JRadioButton();
        proximo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        DatFab = new javax.swing.JTextField();
        jDesktopPane4 = new javax.swing.JDesktopPane();

        jpIdade1.setBackground(new java.awt.Color(255, 255, 255));
        jpIdade1.setBorder(new javax.swing.border.MatteBorder(null));

        jcb1.setBackground(new java.awt.Color(255, 255, 255));
        jcb1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcb1.setForeground(new java.awt.Color(0, 102, 51));
        jcb1.setText("jCheckBox1");
        jcb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb1ActionPerformed(evt);
            }
        });

        jcb2.setBackground(new java.awt.Color(255, 255, 255));
        jcb2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcb2.setForeground(new java.awt.Color(0, 102, 51));
        jcb2.setText("jCheckBox2");

        javax.swing.GroupLayout jpIdade1Layout = new javax.swing.GroupLayout(jpIdade1);
        jpIdade1.setLayout(jpIdade1Layout);
        jpIdade1Layout.setHorizontalGroup(
            jpIdade1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIdade1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jcb1)
                .addGap(47, 47, 47)
                .addComponent(jcb2)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jpIdade1Layout.setVerticalGroup(
            jpIdade1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIdade1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpIdade1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb1)
                    .addComponent(jcb2))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        codigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codigo.setForeground(new java.awt.Color(0, 102, 51));
        codigo.setText("Codigo:");

        jrbF.setBackground(new java.awt.Color(255, 255, 255));
        jrbF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbF.setForeground(new java.awt.Color(0, 102, 51));
        jrbF.setText("F");
        jrbF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(153, 153, 153));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 102, 51));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        sexo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sexo.setForeground(new java.awt.Color(0, 102, 51));
        sexo.setText("Sexo:");

        btnNovo.setBackground(new java.awt.Color(153, 153, 153));
        btnNovo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(0, 102, 51));
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        quantidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quantidade.setForeground(new java.awt.Color(0, 102, 51));
        quantidade.setText("Quantidade");

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtCodigo.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("Cadastro de Bovinos");

        txtQuantidade.setToolTipText("");
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("Data de registro:");

        idade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idade.setForeground(new java.awt.Color(0, 102, 51));
        idade.setText("Classificacao da Idade");

        jrbM.setBackground(new java.awt.Color(255, 255, 255));
        jrbM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbM.setForeground(new java.awt.Color(0, 102, 51));
        jrbM.setText("M");
        jrbM.setToolTipText("");
        jrbM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMActionPerformed(evt);
            }
        });

        jDesktopPane2.setBackground(new java.awt.Color(0, 255, 204));
        jDesktopPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane3.setBackground(new java.awt.Color(102, 102, 102));
        jDesktopPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setText("Cadastro Moto");
        jDesktopPane3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Preço:");
        jDesktopPane3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        Preco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecoActionPerformed(evt);
            }
        });
        jDesktopPane3.add(Preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 230, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Modelo/Marca:");
        jDesktopPane3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        KmRodado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        KmRodado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KmRodadoActionPerformed(evt);
            }
        });
        jDesktopPane3.add(KmRodado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 230, -1));

        Salvar1.setBackground(new java.awt.Color(153, 153, 153));
        Salvar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Salvar1.setText("SALVAR");
        Salvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salvar1ActionPerformed(evt);
            }
        });
        jDesktopPane3.add(Salvar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 90, 30));

        inserir.setBackground(new java.awt.Color(153, 153, 153));
        inserir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inserir.setText("INSERIR");
        inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirActionPerformed(evt);
            }
        });
        jDesktopPane3.add(inserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 100, 30));

        HONDA.setBackground(new java.awt.Color(255, 255, 255));
        HONDA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HONDA.setText("Honda CBR1000rr");
        HONDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HONDAActionPerformed(evt);
            }
        });
        jDesktopPane3.add(HONDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        BMW.setBackground(new java.awt.Color(255, 255, 255));
        BMW.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BMW.setText("BMW - S1000rr");
        BMW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMWActionPerformed(evt);
            }
        });
        jDesktopPane3.add(BMW, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        YAMAHA.setBackground(new java.awt.Color(255, 255, 255));
        YAMAHA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        YAMAHA.setText("Yamaha - yzf R1");
        jDesktopPane3.add(YAMAHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        proximo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        proximo.setText("PRÓXIMO");
        proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoActionPerformed(evt);
            }
        });
        jDesktopPane3.add(proximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 120, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Dat. Fabricação:");
        jDesktopPane3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("KM Rodado:");
        jDesktopPane3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        DatFab.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jDesktopPane3.add(DatFab, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 230, -1));

        jPanel1.add(jDesktopPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 550, 540));

        jTabbedPane1.addTab("Cadastro", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 560));

        jDesktopPane4.setBackground(new java.awt.Color(51, 255, 204));
        jDesktopPane4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jDesktopPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void jcb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb1ActionPerformed

    private void jrbFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbFActionPerformed

    private void jrbMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jrbMActionPerformed

    private void inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirActionPerformed
        // botao novo

        this.HONDA.setSelected(false);
        this.BMW.setSelected(false);
        this.YAMAHA.setSelected(false);

        this.KmRodado.setText("");
        this.Preco.setText("");
    }//GEN-LAST:event_inserirActionPerformed

    private void Salvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salvar1ActionPerformed
        // botao salvar
        try {
            cadastrojogo obj = new cadastrojogo();

            if (HONDA.isSelected()) {
                obj.setCodMarca("1".getText());
                obj.setCodModelo("1".getText());
                obj.setModelo("CBR".getText());
                obj.setMarca(HONDA.getText())
            }

            if (BMW.isSelected()) {
                obj.setCodMarca("2".getText());
                obj.setCodModelo("2".getText());
                obj.setModelo("S1000rr".getText());
                obj.setMarca(BMW.getText());
            }

            if (YAMAHA.isSelected()) {
                obj.setCodMarca("3".getText());
                obj.setCodModelo("3".getText());
                obj.setModelo("yzf R1".getText());
                obj.setMarca(YAMAHA.getText());
            }

            obj.setKmRodado(KmRodado.getText());

            obj.setAnoFab(DatFab.getText());
            
            obj.setPreco(Preco.getText());
            
            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso");

            CadastrarCliente dao = new CadastrarCliente();
            dao.cadastrarFabricante(obj);
            //-------------------------------
        } catch (Exception erro) {

            JOptionPane.showMessageDialog(null, "Erro" + erro);
        }

    }//GEN-LAST:event_Salvar1ActionPerformed

    private void PrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecoActionPerformed

    private void proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoActionPerformed
        Listar CadastroJogo = new Listar();
        CadastroJogo.setVisible(true);
        dispose();
    }//GEN-LAST:event_proximoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void BMWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BMWActionPerformed

    private void HONDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HONDAActionPerformed

    }//GEN-LAST:event_HONDAActionPerformed

    private void KmRodadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KmRodadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KmRodadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BMW;
    private javax.swing.JTextField DatFab;
    private javax.swing.JRadioButton HONDA;
    private javax.swing.JTextField KmRodado;
    private javax.swing.JTextField Preco;
    private javax.swing.JButton Salvar1;
    private javax.swing.JRadioButton YAMAHA;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel idade;
    private javax.swing.JButton inserir;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox jcb1;
    private javax.swing.JCheckBox jcb2;
    private javax.swing.JPanel jpIdade1;
    private javax.swing.JRadioButton jrbF;
    private javax.swing.JRadioButton jrbM;
    private javax.swing.JButton proximo;
    private javax.swing.JLabel quantidade;
    private javax.swing.JLabel sexo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
